repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        files: '^debugwand/.*\.py$'
      # Run the formatter
      - id: ruff-format
        files: '^debugwand/.*\.py$'

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run --group dev pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
      - id: pyright
        name: pyright
        entry: uv run pyright debugwand/
        language: system
        pass_filenames: false
        types: [python]
        stages: [commit]